# Generated by Django 5.1.2 on 2024-11-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fav_recom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='manga_id',
            new_name='manga',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
    ]
