# Generated by Django 5.1.2 on 2024-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='chapters',
            field=models.FileField(upload_to='files/'),
        ),
    ]
