# Generated by Django 5.1.2 on 2024-11-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
