# Generated by Django 5.1.2 on 2024-11-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0002_manga_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='average_rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manga',
            name='popularity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manga',
            name='rating_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
