# Generated by Django 5.1.2 on 2024-11-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0003_manga_average_rating_manga_popularity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='rating',
            new_name='top',
        ),
    ]
