# Generated by Django 5.1.2 on 2024-11-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0004_rename_rating_manga_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='manga',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manga',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manga',
            name='top',
            field=models.IntegerField(default=0),
        ),
    ]
