# Generated by Django 5.1.2 on 2024-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0006_remove_manga_chapters_chaptermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermodel',
            name='premium',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
