# Generated by Django 5.1.2 on 2024-10-09 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='manga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manga.manga'),
        ),
    ]
