# Generated by Django 5.1.2 on 2024-11-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
