# Generated by Django 5.1.2 on 2024-10-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_profile_avatar_alter_profile_fon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
