# Generated by Django 5.1.2 on 2024-11-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_profile_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
