# Generated by Django 5.1.2 on 2024-11-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profile_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
