# Generated by Django 5.1.2 on 2024-10-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Оценка'), (2, 'Оценка'), (3, 'Оценка'), (4, 'Оценка'), (5, 'Оценка')]),
        ),
    ]
